johnDays = float(input("Please enter the number of days John has worked: "))
johnHours = float(input("Please enter the number of hours John has worked: "))
johnMinutes = float(input("Please enter the number of minutes John has worked: "))
billDays = float(input("Please enter the number of days Bill has worked: "))
billHours = float(input("Please enter the number of hours Bill has worked: "))
billMinutes = float(input("Please enter the number of minutes Bill has worked: "))
daysToMinutes = ((johnDays + billDays) * 1440)
hoursToMinutes = ((johnHours + billHours) * 60)
totalMinutes = (billMinutes + johnMinutes + hoursToMinutes + daysToMinutes)
totalDays = int(totalMinutes // 1440)
hoursAndMinutes = totalMinutes % 1440
totalHours = int(hoursAndMinutes // 60)
remainderMinutes = int(hoursAndMinutes % 60)
print("The total time both of them worked together is:", totalDays,"days,", totalHours, "hours and", remainderMinutes, "minutes.")
